### PR TITLE
Wip/add nextclade/mhr

### LINKED ISSUE #2: [REQUEST] Add nextclade
### Feature Request
We want to incorporate nextclade into our analysis for the HA gene. 

### Solution
We will need to select the correct nextclade dataset based on the type/subtype; therefore it might be easiest to incorporate it into the assembly workflow and then merge the results in the summary workflow. 

### Upstream effects
no upstream effects. 

### Downstream effects
syncing data into BigQuery will require a new transfer format that includes nextclade columns. Therefore we will need to add file versions as a suffix to files, like we do for SARS-CoV-2 workflow (new issue request).

### PR DESCRIPTION
**Pull request by molly-hetheringtonrauth**
This PR closes #2 , #4 , and #3 

##  Aim, context, and functionality 🎯
Provide a description of how this pull request addresses each issue that this pull request closes (e.g. provide a brief description for each issue). Provide a description of the changes made. 

This PR, (1) incorporates nextclade for the HA and NA gene segments in the influenza_assembly.wdl, (2) adds version capture to the influenza_assembly.wdl and influenza_assembly_summary.wdl, (3) adds a new task -  ivar assemblies multifasta, (4) removes redunancy in the sequencing results file ({project_name}_sequening_results.csv), (5) renames fasta, bam and vcf files with a new format, and (6) deprecates single end sequencing data (7)  reorganizes the GCP bucket output directory structure for results transfer

_1 - Nextclade_  
Nextclade tasks have been added to the influenza_assemlby.wdl for both the HA and NA gene segments. Captured output files from the task include the nextclade json file, nextclade csv/tsv file, and protein translation fasta files. To accommodate the nextclade updates the following tasks were refactored:

- irma task: 
Each gene segment fasta, bam and vcf file are now individually captured instead of being captured in an array. Fasta, bam and vcf files are grouped into arrays for post qc metrics tasks and transfer tasks. Additionally, a new sample -level multi-fasta file is produced containing all gene segments successfully assembled. 
- samtools_mapped_reads, ivar_consensus, and calc_percent coverage tasks:
Prior these tasks were scattered across the array of input files from the irma task output, now each gene segment has their own samtools_mapped reads, ivar_consensus, and calc_percnet coverage tasks, which are grouped together within an if-statement block, if that gene segment was assembled by IRMA. For the HA and NA gene segments, the nextclade task is also called within this if-statement block. Following all if statement blocks for each gene segment, results are grouped into arrays for the concat_post_qc_metrics and transfer tasks. 
- transfer task:
Nextclade task outputs are added to transfer.

_2 - Version Capture_

- influenza_assemlby.wdl (sample level version capture)
The workflow version is captured in the workflow_version_capture task. The task level version capture is  added to each task using the defined struct "VersionInfo". All version capture output is concatenated into a csv file in the task_version_capture task. A unique version capture file is produced for each sample (sample level version capture) and captured in the wdl output.

- influenza_assembly_summary.wdl (project level version capture)
The workflow version is captured in the workflow_version_capture task. The summary task produces a version capture csv file for the influezna_assmbly_summary.wdl at the project level. Additionally the array of sample version level capture files from the influenza_assemlby.wdl is input into the summary task and the task will concatenate and drops duplicated items creating a version capture file for the influenza_assemlby.wdl at the project level. 

_3-Concatenate ivar assemblies into a sample level multifasta_
Added make_ivar_multifasta task. This task concatenates all gene segments consensus sequences from ivar consensus into a single multifasta. 

_4 - Summary Results File_
- All columns in the wb other than sample name and project name have been dropped from the file.
- software versions and ivar parameters have been removed from the summary results file. 
- results from nextclade including - clade, subclade, short-clade, total substutions, total deletion, total insertions, total frame shifts, total missing, total non ACGTNs, total AA substitutions, total AA deletions, total AA insertions, total unknown AA, nextclade coverage, list of AA substitions, AA delections, AA insertions, warnsing and errors - have been added.

_5- Fasta, bam and vcf file names_
The fasta, bam and vcf file names are now named by their sample name and gene segment only. Flu type and subytpe have been dropped from the file name; however Flu type and subtype remain in the fasta header. 
Previous file names: `{sample_name}_A_HA_H3.fasta`, `{sample_name}_A_MP.fasta`, `{sample_name}_B_HA.fasta`.
New file names: `{sample_name}_HA.fasta`, `{sample_name}_MP.fasta`
Fasta header: `{sample_name}_A_HA_H3`, `{sample_name}_A_MP`, `{sample_name}_B_HA`

_6- Deprecates SE functionary_
Analysis of SE illumina data is no longer supported. This decision was made in order to improve readability of the code.

_7- GCP bucket output directory structure_
The main change is that ivar consensus results, irma bam files, irma vcf files, assembly qc metrics csv file have been pulled out as sub directories of the irma directory and given their own directory. This creates a less nested structure making files and data easier to find and file paths shorter.
```
├── gs://{out_dir}
│   ├── fastqc_raw
│   │   ├── {sample_name}_R1_fastqc.html
│   │   ├── {sample_name}_R1_fastqc.zip
│   │   ├── {sample_name}_R2_fastqc.html
│   │   ├── {sample_name}_R2_fsatqc.zip
|   ├── fastqc_clean
│   │   ├── {sample_name}_R1_fastqc.html
│   │   ├── {sample_name}_R1_fastqc.zip
│   │   ├── {sample_name}_R2_fastqc.html
│   │   ├── {sample_name}_R2_fsatqc.zip
|   ├── seqyclean
│   │   ├── {sample_name}_clean_SummaryStatistics.tsv
|   ├── preprocess_qc_metrics
│   │   ├── {smaple_id}_preprocess_qc_metrics.csv
|   ├── irma_assembly_mutlifasta
|   |   |──{sample_name}_irma.fasta #repeat for each sample
|   ├── irma_assembly_results
|   |   |──{sample_name}_irma_assembled_gene_segments.csv #repeat for each sample
|   ├── irma_alignments
|   |   |──{sample_name} #repeat for each sample
|   |   |   |──{sample_name}_HA.bam
|   |   |   |──{sample_name}_PB1.bam
|   ├── irma_assemblies
|   |   |──{sample_name} #repeat for each sample
|   |   |   |──{sample_name}_HA_irma.fasta # header has full type/subtype description (e.g. A_HA_H3)
|   |   |   |──{sample_name}_PB1_irma.fasta # header has full type/subtype description (e.g. A_PB1)
|   ├── irma_vcfs 
|   |   |──{sample_name} #repeat for each sample
|   |   |   |──{sample_name}_HA.vcf
|   |   |   |──{sample_name}_PB1.vcf
|   ├── ivar_assemblies
|   |   |──{sample_name} #repeat for each sample
|   |   |   |──{sample_name}_HA.fa # header has full type/subtype description (e.g. A_HA_H3)
|   |   |   |──{sample_name}_PB1.fa # header has full type/subtype description (e.g. A_PB1)
|   ├── ivar_assembly_mutlifasta
|   |   |──{sample_name}_ivar.fasta #repeat for each sample
|   ├── assembly_qc_metrics
|   |   |──{sample_name}_qc_metrics.csv #repeat for each sample
|   ├── sorted_bams
|   |   |──{sample_name} #repeat for each sample
|   |   |   |──{sample_name}_HA.sorted.bam 
|   |   |   |──{sample_name}_PB1.sorted.bam 
|   ├── nextclade_out
|   |   |──{sample_name} #repeat for each sample
|   |   |   |──{sample_name}_na_nextclade.json
|   |   |   |──{sample_name}_na_nextclade.tsv
|   |   |   |──{sample_name}_na_translation.fasta
|   |   |   |──{sample_name}_ha_nextclade.json
|   |   |   |──{sample_name}_ha_nextclade.tsv
|   |   |   |──{sample_name}_ha_HA1_translation.fasta
|   |   |   |──{sample_name}_ha_HA2_translation.fasta
|   |   |   |──{sample_name}_ha_SigPep_translation.fasta
│   ├── sumamry_files
|   |   ├── {project_name}_sequencing_results.csv

```

#### Upstream effects 
This code has been written with the anticipated changes of the preprocessing script, with cuts all unnecessary columns from the terra data table and uses string inputs over string array inputs in set level workflows when possible. Thus, the current json input files produced for the influenza workflows will not longer be capable with this version; however in the next version of the preprocessing script the workflow will be compatible with the preprocessing script outputs. 

#### Input changes 
(e.g. file changes, names of data fields, etc.)
_influenza_assembly.wdl_

- fastq_R2 is now a required input.  In accordance with deprecating the SE capability of the workflow. 
- version capture py script is now an input. 

_influenza_assembly_summary.wdl_

- Removed terra data table gcp bucket path. This is in accordance with removing redundancy in the summary results csv file. We no longer need to read in the terra data table to get add all the fields within the terra data table to the summary file; rather that data should only be contained in the workbook.
- The out_bucket_path is now a string rather than an array of strings. This is in accordance with the new updates being applied to the preprocessing script. 
- Version capture file array is added as input.
- Nextclade NA and HA tsv file arrays are added as input.

#### Output changes 
_Output bucket file directory organization_
see 7 under aim, context and functionality

_File Name Changes_
see 5 under aim, context and functionality

_Summary Results File_
See 4 under aim, context and functionality

_Version Capture_
See 2 under aim, context and functionality

#### Downstream effects 
(e.g. BigQuery organization, file structure organization, file content organization)
None - All previous flu runs will be rerun through this updated workflow so that all runs have the same data format. No data has been transferred into BigQuery using earlier versions of the workflow. No tableau views currently use data produce from earlier versions. 

##  Testing 🛠️
**Test dataset(s):**
Flu_0005_miseq. 

**Test(s) performed:**
Ran flu_0005_miseq through the updated workflow (influenza_assembly.wdl and influenza_assembly_summary.wdl). Some inputs were manually set, since the preprocessing script to generate the json input files does not support this updated version. 

**Results (including if the results matched the expected results):**
- GCP bucket was manually inspected to ensure all files were successfully transferred and had correct file names. 
- The summary results file was manually inspected to ensure all expected column headers were included in the file.
- Results including percent coverage, mean depth, num_reads etc, as recorded in the summary results output file were manually inspected for insure values were reasonable.
- Nextclade results for both the NA and HA gene segments were manually checked against results using the nextclade online GUI for a representative sample for H1N1, H3N2, and Bvic.  

## Developer Checklist 👷‍♀️ 
- [x] Prior to development, issues were discussed with the bioinformatics team members and approved
- [x] Code has been refactored to sufficiently address the issues this pull request closes
- [x] Testing was performed and the results from testing match the expected results
- [x] All code changes match our style guide
- [x] README has been updated to reflect changes
- [x] Workflow diagrams in READMEs have been updated to reflect changes

## Reviewer Checklist 🔍
- [x] Met with developer to review all changes and testing performed
- [x] Code refactoring sufficiently address the issue(s) that this pull request closes
- [x] All code meets style guide critera
- [x] Confirm testing was sufficient (e.g. correct dataset was used for testing, results match the expected results). If not, the developer will perform additional testing which should be documented in the testing section above.
- [x] New version release number has been decided upon (if applicable)

### CODE REVIEW

**Comment by molly-hetheringtonrauth** [comment]
To make consistent with SC2, I will need to append the workflow version number to the sequencing results output file name.

**Comment by molly-hetheringtonrauth** [comment]
@laura-bankers - this PR is ready for your review! We will merge this PR into develop for now. I will then work on the CDC IRMA docker issue which will be a new PR at which point we can merge that into develop and then everything into main to create a final version release. Thanks!

**Comment by molly-hetheringtonrauth** [comment]
@laura-bankers - the issue with the number of gene segments being recorded is corrected and this PR is now ready for your review. Basically, I created two columns - "complete_segments" and "assembled_segments". "complete_segments" refer to the number of gene segments with at least 90% coverage at the specified depth of coverage. "assembled_segments" refer to the number  of gene segments assembled by IRMA regardless of depth of coverage or percent coverage.

**Review by laura-bankers — APPROVED** [review]
This is ready to merge into dev

**Pull request merged**
